### ISSUE TITLE
Support new Vector Tile Extension for GPKG

### ISSUE THREAD

**Issue by techmavengeospatial** [ngageoint/geopackage-pbf-js#1]
Write PBF Vector Tiles inside GPKG using Vector Tile Extension and supporting tables
https://github.com/jerstlouis/developer-events/blob/patch-1/2023/Tiling-Interfaces-Code-Sprint/GeoPackage%20Vector%20Tiles%20Extensions.pdf

**Comment by danielbarela** [comment]
We currently do not have resources allocated to support that community extension. If you would like to add support for that extension and submit a pull request, we would be happy to accept it.
